### PR TITLE
use nan v2 and support latest version of node

### PR DESCRIPTION
**Pull request by mmckegg**
This pull request builds on #13 by @thomaschaaf and @sebastianhoitz but updated to support the latest version of nan and node.

### CODE REVIEW

**Comment by adrai** [comment]
Would you like to take the ownership of this module?

**Comment by thomaschaaf** [comment]
Thank you for the continued development! I was about to get this upgraded so you saved me quiet some time :)

**Comment by adrai** [comment]
Who wants to be repo owner and npm module owner? :-)

**Comment by mmckegg** [comment]
@thomaschaaf: I would really appreciate you giving it a look as this is my first time working with C++, Native addons and nan - I really have no idea what I'm doing :laughing:

@adrai: Like I said above, probably not really the best person to take this over, but will do if @thomaschaaf doesn't want to.

**Comment by adrai** [comment]
Just let me know...
I will transfer the repo to someone of you and then give npm rights for both, ok?

**Comment by thomaschaaf** [comment]
Sure transfer it to me and then I can will give permission to @mmckegg aswell :) That way this great module doesn't die!

**Comment by adrai** [comment]
ok... transfer in progress and npm ownership added...

**Pull request merged**
